# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:

  build:
    working_directory: ~/repo
    environment:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    docker:
      - image: circleci/python:3.7.3


    steps:
      - checkout

      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev --deploy
            touch .installed

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run linters
          command: |
            make lint
            pipenv run black src/conduit --check

      - run:
          name: run mypy
          command: |
            make types

      - run:
          name: run tests
          command: |
            make start-pgsql
            make unit

      - run:
          name: run dev app
          command: |
            echo "exit()" >> exit.sh
            cat exit.sh | pipenv run pshell etc/development.ini SKIP_CHECK_DB_MIGRATED=1

      - run:
          name: run prod app
          command: |
            echo "exit()" >> exit.sh
            cat exit.sh | DATABASE_URL="postgresql://conduit_dev@localhost/conduit_dev" pipenv run pshell etc/production.ini SKIP_CHECK_DB_MIGRATED=1
